In [1]:
import pandas as pd

df = pd.read_csv("emails.csv")

# Rename properly
df = df[['text','spam']]
df.columns = ['message','label']

df.head()

                                             message  label
0  Subject: naturally irresistible your corporate...      1
1  Subject: the stock trading gunslinger  fanny i...      1
2  Subject: unbelievable new homes made easy  im ...      1
3  Subject: 4 color printing special  request add...      1
4  Subject: do not have money , get software cds ...      1

In [2]:
print("Shape",df.shape)
print("Columns",df.columns)
print("Missing values",df.isnull().sum())
df['length']=df['message'].apply(len)
print("Average length:\n",df.groupby('label')['length'].mean())
df.head()

Shape (5728, 2)
Columns Index(['message', 'label'], dtype='object')
Missing values message    0
label      0
dtype: int64
Average length:
 label
0    1631.918119
1    1317.257310
Name: length, dtype: float64

                                             message  label  length
0  Subject: naturally irresistible your corporate...      1    1484
1  Subject: the stock trading gunslinger  fanny i...      1     598
2  Subject: unbelievable new homes made easy  im ...      1     448
3  Subject: 4 color printing special  request add...      1     500
4  Subject: do not have money , get software cds ...      1     235

In [3]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
def Clean_text(text):
  text=text.lower()
  text=re.sub(r'[^a-zA-Z]',' ',text)
  words=text.split()
  words = [w for w in words if w not in stopwords.words('english')]
  return ' '.join(words)
df['Clean_Message']=df['message'].apply(Clean_text)
df[['message','Clean_Message']].head()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(df['Clean_Message'])
Y=df['label']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

In [ ]:
stop_words = set(stopwords.words('english'))
def predict_spam(email_text):
    text = email_text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    cleaned_text = " ".join(words)
    vector = vectorizer.transform([cleaned_text])
    prediction = model.predict(vector)[0]
    return "Spam" if prediction == 1 else "Not Spam"

In [ ]:
email = input("Enter your email: ")

result = predict_spam(email)

print("Your email is:", result)